// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB61kGQPC9ESTP07-jdCfbSYiiRSOsxmA',
    appId: '1:672723588311:web:a23d1a6af4e14907698c92',
    messagingSenderId: '672723588311',
    projectId: 'mobileapp-9e32a',
    authDomain: 'mobileapp-9e32a.firebaseapp.com',
    storageBucket: 'mobileapp-9e32a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW8WbVzBWsaQ1rPpD-wyZwlbcww6_6s5k',
    appId: '1:672723588311:android:d63cd9910efa0376698c92',
    messagingSenderId: '672723588311',
    projectId: 'mobileapp-9e32a',
    storageBucket: 'mobileapp-9e32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsY6cHPRCAt9RJRfilThgizU1IfINFCtA',
    appId: '1:672723588311:ios:1c312fcbb3947941698c92',
    messagingSenderId: '672723588311',
    projectId: 'mobileapp-9e32a',
    storageBucket: 'mobileapp-9e32a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsY6cHPRCAt9RJRfilThgizU1IfINFCtA',
    appId: '1:672723588311:ios:1c312fcbb3947941698c92',
    messagingSenderId: '672723588311',
    projectId: 'mobileapp-9e32a',
    storageBucket: 'mobileapp-9e32a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB61kGQPC9ESTP07-jdCfbSYiiRSOsxmA',
    appId: '1:672723588311:web:771fdb6bcfd1aa00698c92',
    messagingSenderId: '672723588311',
    projectId: 'mobileapp-9e32a',
    authDomain: 'mobileapp-9e32a.firebaseapp.com',
    storageBucket: 'mobileapp-9e32a.appspot.com',
  );
}
